#!/bin/sh
# Configuration variables to automate the VPN setup
# Set some default values

# Network variables
SERVER_LOCAL_IP=192.168.1.5
SERVER_PUBLIC_IP=123.456.789.123
LAN_IP=192.168.1.0
GATEWAY_IP=192.168.1.1

# User variables
KEY_SIZE=2048
VPN_PORT=1194
IFACE_TYPE=eth0 # set to wlan0 for wireless server

SERVER_NAME=my_vpn_server
CLIENT_NAME=my_vpn_client

# Utility function
read_input(){
    question="$1"
    default="$2"
    # Get a carriage return into `cr` -- there *has* to be a better way to do 
    # this
    #cr=`echo $'\n.'`
    #cr=${cr%.}
    q="$1 ($2)? "
    read -rp "$q" ans
    if [ -n "$ans" ]; then
        printf '%s' "$ans"
    else
        printf '%s' "$default"
    fi
}


# Setup network variables
echo Trying to figure out your network configuration . . .
echo "Press enter to keep the default choice.\n"

# Set network interface
IFACE_TYPE=$( read_input "Use eth0 or wlan0 network interface" $IFACE_TYPE )

# Set server local ip
SERVER_LOCAL_IP=$(ip addr show $IFACE_TYPE | grep "inet" | grep -v "inet6" | awk '{print 
$2}' | cut -d '/' -f 1)
SERVER_LOCAL_IP=$( read_input "Local ip address" $SERVER_LOCAL_IP )

# Set server public ip
SERVER_PUBLIC_IP=$(wget http://ipinfo.io/ip -qO -)
SERVER_PUBLIC_IP=$( read_input "Public ip address" $SERVER_PUBLIC_IP )


# Set gateway ip
GATEWAY_IP=$( netstat -nr | head -3 | tail -1 | awk '{print $2}' )
GATEWAY_IP=$( read_input "Gateway(router) ip address" $GATEWAY_IP )

# Set LAN ip
LAN_IP=$( netstat -nr | tail -1 | awk '{print $1}' )
LAN_IP=$( read_input "Local subnet ip address" $LAN_IP )

# Setup user variables
echo "\nA few more to go . . ."
echo "Press enter to keep the default choice.\n"

VPN_PORT=$( read_input "Pick a port allowing VPN connections on your server" $VPN_PORT ) 
KEY_SIZE=$( read_input "Choose authentication key size" $KEY_SIZE ) 
SERVER_NAME=$( read_input "Pick a name for your server" $SERVER_NAME ) 
CLIENT_NAME=$( read_input "Pick a name for your client" $CLIENT_NAME ) 


echo Done!
echo "This is your configuration:\n"
echo "Network interface: $IFACE_TYPE"
echo "Local IP:          $SERVER_LOCAL_IP"
echo "Public IP:         $SERVER_PUBLIC_IP"
echo "Gateway IP:        $GATEWAY_IP"
echo "Local subnet IP:   $LAN_IP"
echo "VPN port:          $VPN_PORT"
echo "Key size:          $KEY_SIZE"
echo "Server name:       $SERVER_NAME"
echo "Client name:       $CLIENT_NAME"






