IFACE_TYPE: 'eth0'
SERVER_LOCAL_IP: 127.0.0.1
SERVER_PUBLIC_IP: 88.217.181.245
GATEWAY_IP: 192.168.178.1
LAN_IP: 192.168.178.0
VPN_PORT: 1194
KEY_SIZE: 2048
SERVER_NAME: my_awesome_server
CLIENT_NAMES:     ['vpn_client1', 'vpn_client2']
