CLIENT_NAMES: !!set
  alekos: null
  dora: null
GATEWAY_IP: 192.168.178.1
IFACE_TYPE: wlan0
KEY_SIZE: '2048'
LAN_IP: 192.168.178.0
SERVER_LOCAL_IP: 192.168.178.21
SERVER_NAME: my_vpn_server
SERVER_PUBLIC_IP: 12.234.123.231
VPN_PORT: '1194'
